language: go

git:
  depth: false

sudo: required

dist: xenial

services:
  - docker

go:
  - 1.13

before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md)|(\.png)|(\.pdf)|(\.html)|^(LICENSE)|^(docs)'
    then
      echo "Only doc files were updated, skip running the CI."
      travis_terminate 0
    fi

install: true

jobs:
  include:
    - stage: "Compile"
      name: "Compile"
      before_script:
      script:
        - make opentelekomcloud-controller-manager
    - stage: "Verify"
      name: "Verify gofmt, golint, etc"
      before_script:
      script:
        - make verify
    - stage: "Unit test"
      name: "go test"
      before_script:
      script:
        - make test
